#!/bin/sh

set -o errexit
set -o nounset

# Change string 'spotify' for your project_name
celery flower \
    --app=spotify.taskapp \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
